//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMG.DataSyncTool.Library.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GMG.DataSyncTool.Library.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WITH fk_tables
        ///     AS (SELECT
        ///           s1.name AS from_schema,
        ///           o1.Name AS from_table,
        ///           s2.name AS to_schema,
        ///           o2.Name AS to_table
        ///         FROM
        ///           sys.foreign_keys fk
        ///           INNER JOIN sys.objects o1
        ///                   ON fk.parent_object_id = o1.object_id
        ///           INNER JOIN sys.schemas s1
        ///                   ON o1.schema_id = s1.schema_id
        ///           INNER JOIN sys.objects o2
        ///                   ON fk.referenced_object_id = o2.object_id
        ///           [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DependencyOrderScript {
            get {
                return ResourceManager.GetString("DependencyOrderScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///  KCU.TABLE_SCHEMA SchemaName,
        ///  KCU.TABLE_NAME  AS TableName,
        ///  KCU.COLUMN_NAME AS ColumnName
        ///FROM
        ///  INFORMATION_SCHEMA.TABLE_CONSTRAINTS TC
        ///  JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE KCU
        ///    ON KCU.CONSTRAINT_SCHEMA = TC.CONSTRAINT_SCHEMA
        ///   AND KCU.CONSTRAINT_NAME = TC.CONSTRAINT_NAME
        ///   AND KCU.TABLE_SCHEMA = TC.TABLE_SCHEMA
        ///   AND KCU.TABLE_NAME = TC.TABLE_NAME
        ///WHERE
        ///  TC.CONSTRAINT_TYPE = &apos;PRIMARY KEY&apos;
        ///ORDER  BY
        ///  KCU.TABLE_SCHEMA,
        ///  KCU.TABLE_NAME,
        ///  KCU.CONSTRAINT_NAME 
        ///.
        /// </summary>
        internal static string PrimaryKeyColumnsScript {
            get {
                return ResourceManager.GetString("PrimaryKeyColumnsScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///  TABLE_CATALOG            AS CatalogName,
        ///  TABLE_SCHEMA             AS SchemaName,
        ///  TABLE_NAME               AS TableName,
        ///  COLUMN_NAME              AS ColumnName,
        ///  ORDINAL_POSITION         AS Position,
        ///  COLUMN_DEFAULT           AS ColumnDefault,
        ///  IS_NULLABLE              AS IsNullable,
        ///  DATA_TYPE                AS DataType,
        ///  CHARACTER_MAXIMUM_LENGTH AS MaxCharacterLength,
        ///  NUMERIC_PRECISION        AS NumericPrecision
        ///FROM
        ///  INFORMATION_SCHEMA.COLUMNS 
        ///.
        /// </summary>
        internal static string TableColumnScript {
            get {
                return ResourceManager.GetString("TableColumnScript", resourceCulture);
            }
        }
    }
}
